name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker image and run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v5
      
      - name: Run end-to-end tests
        run: >
          docker compose --profile testing up
          --build --exit-code-from test-service

      # временно отключено условием [false &&]
      - name: Login to Docker Hub
        if: false && ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # временно отключено условием [false &&]
      - name: Push image to Docker Hub
        if: false && ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/page-tracker:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/page-tracker:latest
            
          
          
        
